# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4

EAPI=8

CRATES="
	aho-corasick-1.1.3
	bitflags-2.6.0
	clock_ticks-0.1.1
	env_filter-0.1.2
	env_logger-0.11.5
	equivalent-1.0.1
	fix-getters-rules-0.3.2
	getopts-0.2.21
	hashbrown-0.15.0
	hprof-0.1.3
	indexmap-2.6.0
	log-0.3.9
	log-0.4.22
	memchr-2.7.4
	once_cell-1.20.2
	proc-macro2-1.0.89
	quote-1.0.37
	regex-1.11.1
	regex-automata-0.4.8
	regex-syntax-0.8.5
	rustdoc-stripper-0.1.19
	serde-1.0.214
	serde_derive-1.0.214
	serde_spanned-0.6.8
	syn-2.0.85
	toml-0.8.19
	toml_datetime-0.6.8
	toml_edit-0.22.22
	unicode-ident-1.0.13
	unicode-width-0.1.14
	winnow-0.6.20
	xml-rs-0.8.22
"

inherit cargo

DESCRIPTION="gir"
HOMEPAGE="https://gtk-rs.org/"
SRC_URI="$(cargo_crate_uris)"
SRC_URI="\
	https://github.com/gtk-rs/${PN}/archive/refs/tags/${PV}.tar.gz -> ${P}.tar.gz \
	${CARGO_CRATE_URIS}"

# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="Apache-2.0 Boost-1.0 MIT Unicode-DFS-2016 Unlicense"
SLOT="0"
KEYWORDS="~amd64 ~arm64"

DEPEND=""
RDEPEND="${DEPEND}"
BDEPEND=""

PATCHES=(
	"${FILESDIR}/0001-Use-rustdoc-stripper-0.1.19-from-crates.io.patch"
	"${FILESDIR}/0002-Manually-override-version-string.patch"
)

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"
