# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4-r1

EAPI=8

CRATES="
	aho-corasick@1.1.2
	bitflags@2.5.0
	clock_ticks@0.1.1
	env_filter@0.1.0
	env_logger@0.11.3
	equivalent@1.0.1
	fix-getters-rules@0.3.2
	getopts@0.2.21
	hashbrown@0.14.3
	hprof@0.1.3
	indexmap@2.1.0
	log@0.3.9
	log@0.4.21
	memchr@2.7.1
	once_cell@1.19.0
	proc-macro2@1.0.78
	quote@1.0.35
	regex@1.10.4
	regex-automata@0.4.5
	regex-syntax@0.8.2
	rustdoc-stripper@0.1.19
	serde@1.0.195
	serde_derive@1.0.195
	serde_spanned@0.6.5
	syn@2.0.48
	toml@0.8.12
	toml_datetime@0.6.5
	toml_edit@0.22.9
	unicode-ident@1.0.12
	unicode-width@0.1.11
	winnow@0.6.5
	xml-rs@0.8.20
"

inherit cargo

DESCRIPTION="gir"
HOMEPAGE="https://gtk-rs.org/"
SRC_URI="\
	https://github.com/gtk-rs/${PN}/archive/refs/tags/${PV}.tar.gz -> ${P}.tar.gz \
	${CARGO_CRATE_URIS}"

LICENSE="Apache-2.0 Boost-1.0 MIT Unicode-DFS-2016 Unlicense"
SLOT="0"
KEYWORDS="~amd64 ~arm64"

DEPEND=""
RDEPEND="${DEPEND}"
BDEPEND=""

PATCHES=(
	"${FILESDIR}/0001-Use-rustdoc-stripper-0.1.19-from-crates.io.patch"
	"${FILESDIR}/0002-Manually-override-version-string.patch"
)

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"
